---
- name: Common Configuration
  hosts: all
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install common packages
      apt:
        name:
          - curl
          - wget
          - unzip
          - git
          - vim
          - htop
        state: present

    - name: Disable swap
      shell: swapoff -a

#########################################################

- name: Install Docker
  hosts: all
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

#########################################################

- name: Install Kubernetes Tools
  hosts: k8s_master,k8s_workers
  become: yes

  tasks:

    - name: Install dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
        state: present

    - name: Add Kubernetes repo
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | \
        gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] \
        https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' \
        > /etc/apt/sources.list.d/kubernetes.list

    - name: Update apt
      apt:
        update_cache: yes

    - name: Install kubeadm kubelet kubectl
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: present

#########################################################

- name: Configure Jenkins Server
  hosts: jenkins
  become: yes

  tasks:

    - name: Install Java
      apt:
        name: openjdk-21-jdk
        state: present

    - name: Install NodeJS
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt install -y nodejs

    - name: Install Maven
      apt:
        name: maven
        state: present

    - name: Install Trivy
      shell: |
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb generic main | tee -a /etc/apt/sources.list.d/trivy.list
        apt update
        apt install trivy -y

#########################################################

- name: Initialize Kubernetes Master
  hosts: k8s_master
  become: yes

  tasks:

    - name: Initialize cluster
      shell: |
        kubeadm init --pod-network-cidr=192.168.0.0/16
      ignore_errors: yes
