apiVersion: v1
kind: Service

metadata:
  name: payment-service
  namespaces: dev

spec:
  selector:
    app: payment-service

  ports:
  - protocol: TCP
    port: 3007
    targetPort: 3007

  type: ClusterIP
