apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: production  # रूट वाली फाइल्स प्रोडक्शन नेमस्पेस के लिए हैं!
  labels:
    app: auth-service
spec:
  replicas: 3  # प्रॉडक्शन में लोड झेलने के लिए कम से कम 3 रेप्लिका
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        # यह Docker Hub के बजाय तुम्हारी AWS ECR रिपॉजिटरी से इमेज खींचेगा
        # जेनकिंस पाइपलाइन चलते समय इस 'latest' शब्द को असली प्रॉडक्शन टैग (जैसे prod-b12) से बदल देगी
        image: REPLACE_WITH_AWS_ECR_URL/auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080 # हमारी प्रोडक्शन डॉकरफाइल का स्टैंडर्ड पोर्ट
        env:
        - name: DB_HOST
          value: "REPLACE_WITH_YOUR_RDS_ENDPOINT_FROM_TERRAFORM_APPLY"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: production
spec:
  type: ClusterIP  # पूरी तरह सुरक्षित इंटरनल नेटवर्किंग
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
