apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: production  # रूट वाली फाइल्स प्रोडक्शन नेमस्पेस के लिए हैं!
  labels:
    app: product-service
spec:
  replicas: 1  # प्रॉडक्शन में लोड झेलने के लिए कम से कम 3 रेप्लिका
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        # यह Docker Hub के बजाय तुम्हारी AWS ECR रिपॉजिटरी से इमेज खींचेगा
        # जेनकिंस पाइपलाइन चलते समय इस 'latest' शब्द को असली प्रॉडक्शन टैग (जैसे prod-b12) से बदल देगी
        image: REPLACE_WITH_AWS_ECR_URL/product-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080  # हमारी प्रोडक्शन डॉकरफाइल का स्टैंडर्ड पोर्ट
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: production
spec:
  type: ClusterIP  # पूरी तरह सुरक्षित इंटरनल नेटवर्किंग
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
