apiVersion: v1
kind: Service

metadata:
  name: product-service
  namespaces: dev

spec:
  selector:
    app: product-service

  ports:
  - protocol: TCP
    port: 3008
    targetPort: 3008

  type: ClusterIP
