apiVersion: v1
kind: Service

metadata:
  name: wishlist-service
  namespaces: dev

spec:
  selector:
    app: wishlist-service

  ports:
  - protocol: TCP
    port: 3014
    targetPort: 3014

  type: ClusterIP
