---
- name: Basic Server Setup
  hosts: all
  become: yes

  tasks:

    - name: Update packages
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install NodeJS
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
        apt install -y nodejs

    - name: Install kubectl
      apt:
        name: kubectl
        state: present

    - name: Install Trivy
      shell: |
        apt install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | tee /etc/apt/sources.list.d/trivy.list
        apt update
        apt install trivy -y
