apiVersion: apps/v1
kind: Deployment

metadata:
  name: discount-service
  namespaces: dev

spec:
  replicas: 2

  selector:
    matchLabels:
      app: discount-service

  template:
    metadata:
      labels:
        app: discount-service

    spec:
      containers:
      - name: discount-service
        image: praveen230389/discount-service:latest

        ports:
        - containerPort: 3003
