pipeline {

    agent any

    stages {

        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Deploy To Dev Namespace') {
            steps {
                sh 'kubectl apply -f k8s/ -n dev'
            }
        }

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods -n dev'
            }
        }
    }

    post {

        success {
            echo 'DEV Deployment Successful'
        }

        failure {
            echo 'DEV Deployment Failed'
        }
    }
}
